### 1. Obtener datos de un usuario de prueba
GET https://jsonplaceholder.typicode.com/users/1

### 2. Obtener una tarea pendiente
GET https://jsonplaceholder.typicode.com/todos/1

### 3. Crear un nuevo usuario (POST)
POST https://jsonplaceholder.typicode.com/users
Content-Type: application/json

{
    "name": "Fer",
    "email": "fer@test.com"
}

### 4. Consultar lista completa de usuarios existentes
GET https://jsonplaceholder.typicode.com/users

### 5. Consultar un usuario específico existente por ID
GET https://jsonplaceholder.typicode.com/users/2